version: "3.6"

services:
  db:
    environment:
      - POSTGRES_PASSWORD=postgis
    image: mdillon/postgis:10-alpine
    ports:
      - "5432:5432"
    volumes:
      - timeline_db:/var/lib/postgresql/data

  # Civ's Log server. An Express REST server
  server:
    image: node:9-alpine
    command: ["npm", "run", "start:dev"]
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PGHOST: db
    ports:
      - "3377:3377"
    secrets:
      - civslog_db_name
      - civslog_db_user
      - civslog_db_password
    user: node
    volumes:
      - ./node_modules/civslog-server:/app
    working_dir: /app

  # Civ's Log client. Also an Express webserver, but solemnly serving the index.html
  # and proxying towards Civ's Log REST server
  client:
    image: node:9-alpine
    command: ["npm", "run", "start:server:dev"]
    depends_on:
      - server 
    environment:
      NODE_ENV: development
      CIVSLOG_SERVER: server
    ports:
      - "3000:3000"
      - "9856:9856"
    user: node
    volumes:
      - ./:/app
      - ./node_modules/halicarnassus:/app/node_modules/halicarnassus
      - ./node_modules/timeline:/app/node_modules/timeline
    working_dir: /app

volumes:
  timeline_db:

secrets:
  civslog_db_name:
    external: true
  civslog_db_user:
    external: true
  civslog_db_password:
    external: true